# Generated by Django 4.0.4 on 2022-04-26 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tessereunimore',
            name='mail',
            field=models.TextField(default='def', unique=True),
            preserve_default=False,
        ),
    ]
