# Generated by Django 4.0.4 on 2022-04-26 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_tessereunimore_mail'),
    ]

    operations = [
        migrations.AddField(
            model_name='tessereunimore',
            name='password',
            field=models.TextField(blank=True, null=True),
        ),
    ]
