# Generated by Django 4.0.4 on 2022-05-09 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_tessereunimore_password'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='biblioteche',
            options={'verbose_name_plural': 'biblioteche'},
        ),
        migrations.AlterModelOptions(
            name='tessereunimore',
            options={'verbose_name_plural': 'tessere UniMoRe'},
        ),
        migrations.RemoveField(
            model_name='tessereunimore',
            name='password',
        ),
        migrations.AddField(
            model_name='tessereunimore',
            name='is_registered',
            field=models.TextField(blank=True, verbose_name='registrato su app'),
        ),
        migrations.AlterField(
            model_name='biblioteche',
            name='capienza',
            field=models.IntegerField(blank=True, null=True, verbose_name='capienza massima'),
        ),
        migrations.AlterField(
            model_name='biblioteche',
            name='count',
            field=models.IntegerField(blank=True, null=True, verbose_name='conteggio attuale'),
        ),
        migrations.AlterField(
            model_name='biblioteche',
            name='nome',
            field=models.TextField(blank=True, primary_key=True, serialize=False, verbose_name='nome biblioteca'),
        ),
        migrations.AlterField(
            model_name='tessereunimore',
            name='facolta',
            field=models.TextField(blank=True, null=True, verbose_name='facoltà'),
        ),
        migrations.AlterField(
            model_name='tessereunimore',
            name='mail',
            field=models.TextField(blank=True, null=True, unique=True, verbose_name='email di Ateneo'),
        ),
    ]
