# Generated by Django 4.0.4 on 2022-05-09 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_biblioteche_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tessereunimore',
            name='is_registered',
            field=models.BooleanField(blank=True, verbose_name='registrato su app'),
        ),
    ]
