# Generated by Django 4.0.2 on 2022-05-11 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_tessereunimore_is_registered'),
    ]

    operations = [
        migrations.AddField(
            model_name='biblioteche',
            name='exstension',
            field=models.TextField(blank=True, null=True, verbose_name='dizionario_estensioni'),
        ),
        migrations.AddField(
            model_name='biblioteche',
            name='is_extended',
            field=models.BooleanField(blank=True, null=True, verbose_name='aula_estesa'),
        ),
    ]
