# Generated by Django 4.0.2 on 2022-05-11 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_biblioteche_exstension_biblioteche_is_extended'),
    ]

    operations = [
        migrations.RenameField(
            model_name='biblioteche',
            old_name='exstension',
            new_name='extension',
        ),
    ]
