# Generated by Django 4.0.4 on 2022-05-11 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_rename_exstension_biblioteche_extension'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biblioteche',
            name='extension',
            field=models.TextField(blank=True, null=True, verbose_name='info aula estesa'),
        ),
        migrations.AlterField(
            model_name='biblioteche',
            name='is_extended',
            field=models.BooleanField(blank=True, null=True, verbose_name='esteso?'),
        ),
    ]
