# Generated by Django 4.0.4 on 2022-05-13 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_biblioteche_extension_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='biblioteche',
            name='opening_hours',
            field=models.TextField(blank=True, null=True, verbose_name='orari di apertura'),
        ),
    ]
