# Generated by Django 4.0.2 on 2022-05-19 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_biblioteche_opening_hours'),
    ]

    operations = [
        migrations.CreateModel(
            name='RewardsLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_user', models.TextField(blank=True, verbose_name='codice utente')),
                ('date', models.TextField(blank=True, verbose_name='data della suggestion')),
                ('suggestion', models.TextField(verbose_name='suggestion')),
            ],
            options={
                'db_table': 'rewars_log',
            },
        ),
        migrations.AddConstraint(
            model_name='rewardslog',
            constraint=models.UniqueConstraint(fields=('id_user', 'date'), name='id_for_a_date'),
        ),
    ]
