# Generated by Django 4.0.2 on 2022-05-19 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_rewardslog_rewardslog_id_for_a_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rewardslog',
            name='id',
        ),
        migrations.AlterField(
            model_name='rewardslog',
            name='id_user',
            field=models.TextField(blank=True, primary_key=True, serialize=False, verbose_name='codice utente'),
        ),
    ]
