# Generated by Django 4.0.2 on 2022-05-19 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_remove_rewardslog_id_alter_rewardslog_id_user'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='rewardslog',
            table='rewards_log',
        ),
    ]
