# Generated by Django 4.0.2 on 2022-05-24 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_rewardslog'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogUnimo',
            fields=[
                ('timestamp', models.TextField(blank=True, primary_key=True, serialize=False)),
                ('mode', models.TextField(blank=True, null=True)),
                ('facolta', models.TextField(default='ingmo')),
            ],
            options={
                'db_table': 'log_unimo',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='LogIngmo',
        ),
    ]
