# Generated by Django 4.0.4 on 2022-05-24 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_logunimo_delete_logingmo'),
    ]

    operations = [
        migrations.AddField(
            model_name='tessereunimore',
            name='rewards_counter',
            field=models.IntegerField(default=0, verbose_name='contatore dei rewards ottenuti'),
        ),
    ]
