# Generated by Django 4.0.4 on 2022-05-24 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_tessereunimore_rewards_counter'),
    ]

    operations = [
        migrations.AddField(
            model_name='tessereunimore',
            name='rewards_lastmodified',
            field=models.TextField(null=True, verbose_name='data modifica del contatore rewards'),
        ),
    ]
