# Generated by Django 4.0.4 on 2022-06-03 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_tessereunimore_telegram_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='biblioteche',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='indirizzo'),
        ),
    ]
